notion_api:
  api_key: secret_ltDrFCJCsii993OGj1uPtBWQBAfTfGFjX5Vc24khVmK
  api_version: 2022-06-28
  databases:
    tasks:
      id: 4abee5c8be33483ab39d092ff004d45f
      title: "Tasks"
      fields: ["Name", "Data", "Feita"]
    projects:
      id: 1428e204c58a411aa10e373cbf64c10c
      title: "Projects"
      fields: ["Name", "Data de inicio", "Data final", "Progresso"]
    birthdays:
      id: 1a01a8e7052b43bdb8c30ea74400a9f4
      title: "Birthdays"
      fields: ["Name", "Data", "icons"]
