[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build-meta"

[project]
name = "notionpy"
version = "0.0.1"

[tool.ruff]
line-length = 120

[tools.setuptools.packages.find]
namespaces = false
