notion_api:
  api_key: SECRET_KEY 
  api_version: 2022-06-28
  databases:
    tasks:
      id: <your-database-id>
      title: <your-database-title>
      fields: <your-database-fields>
    projects:
      id: <your-database-id>
      title: <your-database-title>
      fields: <your-database-fields>
    birthdays:
      id: <your-database-id>
      title: <your-database-title>
      fields: <your-database-fields>
